// AUTO-GENERATED by scripts/generate-asset-registry.mjs — do not edit manually
import type { AssetMeta } from '../types/assets';

export const ASSET_REGISTRY: AssetMeta[] = [
  {
    "id": "backgrounds-placeholder-bg",
    "filename": "placeholder-bg.png",
    "type": "background",
    "url": "/assets/backgrounds/placeholder-bg.png",
    "category": "backgrounds",
    "hidden": false
  },
  {
    "id": "characters-background-bg_final_clearing",
    "filename": "BG_FINAL_CLEARING.png",
    "type": "background",
    "url": "/assets/Characters/BACKGROUND/BG_FINAL_CLEARING.png",
    "category": "BACKGROUND",
    "hidden": false
  },
  {
    "id": "characters-background-bg_forest_chase",
    "filename": "BG_FOREST_CHASE.png",
    "type": "background",
    "url": "/assets/Characters/BACKGROUND/BG_FOREST_CHASE.png",
    "category": "BACKGROUND",
    "hidden": false
  },
  {
    "id": "characters-background-bg_forest_clearing",
    "filename": "BG_FOREST_CLEARING.png",
    "type": "background",
    "url": "/assets/Characters/BACKGROUND/BG_FOREST_CLEARING.png",
    "category": "BACKGROUND",
    "hidden": false
  },
  {
    "id": "characters-background-bg_forest_main",
    "filename": "BG_FOREST_MAIN.png",
    "type": "background",
    "url": "/assets/Characters/BACKGROUND/BG_FOREST_MAIN.png",
    "category": "BACKGROUND",
    "hidden": false
  },
  {
    "id": "characters-background-bg_forest_nest",
    "filename": "BG_FOREST_NEST.png",
    "type": "background",
    "url": "/assets/Characters/BACKGROUND/BG_FOREST_NEST.png",
    "category": "BACKGROUND",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_emotions_sheet",
    "filename": "BOGO_EMOTIONS_SHEET.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_EMOTIONS_SHEET.png",
    "category": "BOGO",
    "hidden": true
  },
  {
    "id": "characters-bogo-bogo_face_left_surprised",
    "filename": "BOGO_FACE_LEFT_SURPRISED.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_FACE_LEFT_SURPRISED.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_face_left",
    "filename": "BOGO_FACE_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_FACE_LEFT.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_face_right_surprised",
    "filename": "BOGO_FACE_RIGHT_SURPRISED.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_FACE_RIGHT_SURPRISED.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_face_right",
    "filename": "BOGO_FACE_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_FACE_RIGHT.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_jump",
    "filename": "BOGO_JUMP.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_JUMP.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_left_surprised",
    "filename": "BOGO_LEFT_SURPRISED.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_LEFT_SURPRISED.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_neutral",
    "filename": "BOGO_NEUTRAL.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_NEUTRAL.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_point_left",
    "filename": "BOGO_POINT_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_POINT_LEFT.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_point_right",
    "filename": "BOGO_POINT_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_POINT_RIGHT.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_reference_sheet",
    "filename": "BOGO_REFERENCE_SHEET.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_REFERENCE_SHEET.png",
    "category": "BOGO",
    "hidden": true
  },
  {
    "id": "characters-bogo-bogo_right_surprised",
    "filename": "BOGO_RIGHT_SURPRISED.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_RIGHT_SURPRISED.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_run_left",
    "filename": "BOGO_RUN_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_RUN_LEFT.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_run_right",
    "filename": "BOGO_RUN_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_RUN_RIGHT.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_walk_left",
    "filename": "BOGO_WALK_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_WALK_LEFT.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_walk_right",
    "filename": "BOGO_WALK_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_WALK_RIGHT.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo_wave",
    "filename": "BOGO_WAVE.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO_WAVE.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-bogo-bogo",
    "filename": "BOGO.png",
    "type": "character",
    "url": "/assets/Characters/BOGO/BOGO.png",
    "category": "BOGO",
    "hidden": false
  },
  {
    "id": "characters-pip-pip_emotions_sheet",
    "filename": "PIP_EMOTIONS_SHEET.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_EMOTIONS_SHEET.png",
    "category": "PIP",
    "hidden": true
  },
  {
    "id": "characters-pip-pip_fly_left",
    "filename": "PIP_FLY_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_FLY_LEFT.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pip-pip_fly_right",
    "filename": "PIP_FLY_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_FLY_RIGHT.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pip-pip_neutral",
    "filename": "PIP_NEUTRAL.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_NEUTRAL.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pip-pip_point_left",
    "filename": "PIP_POINT_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_POINT_LEFT.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pip-pip_point_right",
    "filename": "PIP_POINT_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_POINT_RIGHT.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pip-pip_reference_sheet",
    "filename": "PIP_REFERENCE_SHEET.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_REFERENCE_SHEET.png",
    "category": "PIP",
    "hidden": true
  },
  {
    "id": "characters-pip-pip_run_left",
    "filename": "PIP_RUN_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_RUN_LEFT.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pip-pip_run_right",
    "filename": "PIP_RUN_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_RUN_RIGHT.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pip-pip_walk_left",
    "filename": "PIP_WALK_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_WALK_LEFT.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pip-pip_walk_right",
    "filename": "PIP_WALK_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_WALK_RIGHT.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pip-pip_wave",
    "filename": "PIP_WAVE.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP_WAVE.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pip-pip",
    "filename": "PIP.png",
    "type": "character",
    "url": "/assets/Characters/PIP/PIP.png",
    "category": "PIP",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_curious",
    "filename": "POGO_CURIOUS.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_CURIOUS.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_emotions_sheet",
    "filename": "POGO_EMOTIONS_SHEET.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_EMOTIONS_SHEET.png",
    "category": "POGO",
    "hidden": true
  },
  {
    "id": "characters-pogo-pogo_face_left",
    "filename": "POGO_FACE_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_FACE_LEFT.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_face_right",
    "filename": "POGO_FACE_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_FACE_RIGHT.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_jump",
    "filename": "POGO_JUMP.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_JUMP.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_neutral",
    "filename": "POGO_NEUTRAL.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_NEUTRAL.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_pointing_left",
    "filename": "POGO_POINTING_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_POINTING_LEFT.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_pointing_right",
    "filename": "POGO_POINTING_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_POINTING_RIGHT.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_reference_sheet",
    "filename": "POGO_REFERENCE_SHEET.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_REFERENCE_SHEET.png",
    "category": "POGO",
    "hidden": true
  },
  {
    "id": "characters-pogo-pogo_run_left",
    "filename": "POGO_RUN_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_RUN_LEFT.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_run_right",
    "filename": "POGO_RUN_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_RUN_RIGHT.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_surprised",
    "filename": "POGO_SURPRISED.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_SURPRISED.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_walk_left",
    "filename": "POGO_WALK_LEFT.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_WALK_LEFT.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_walk_right",
    "filename": "POGO_WALK_RIGHT.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_WALK_RIGHT.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo_wave",
    "filename": "POGO_WAVE.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO_WAVE.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-pogo-pogo",
    "filename": "POGO.png",
    "type": "character",
    "url": "/assets/Characters/POGO/POGO.png",
    "category": "POGO",
    "hidden": false
  },
  {
    "id": "characters-props-giant_egg_crack",
    "filename": "GIANT_EGG_CRACK.png",
    "type": "prop",
    "url": "/assets/Characters/PROPS/GIANT_EGG_CRACK.png",
    "category": "PROPS",
    "hidden": false
  },
  {
    "id": "characters-props-giant_egg",
    "filename": "GIANT_EGG.png",
    "type": "prop",
    "url": "/assets/Characters/PROPS/GIANT_EGG.png",
    "category": "PROPS",
    "hidden": false
  }
];

export function getAssetById(id: string): AssetMeta | undefined {
  return ASSET_REGISTRY.find((a) => a.id === id);
}

export function getAssetsByType(type: AssetMeta['type']): AssetMeta[] {
  return ASSET_REGISTRY.filter((a) => a.type === type && !a.hidden);
}

export function getAssetsByCategory(category: string): AssetMeta[] {
  return ASSET_REGISTRY.filter((a) => a.category === category && !a.hidden);
}

export function getCategories(): string[] {
  const cats = new Set(ASSET_REGISTRY.filter((a) => !a.hidden).map((a) => a.category ?? 'misc'));
  return [...cats].sort();
}
